### PR TITLE
Fixes issue causing parcelable collections types not to be recognized. Fixes #7

### LINKED ISSUE #7: Parcelability detection erroneously fails on List<String>
```java
@AutoValue
public abstract class Foo {
  public abstract List<String> bar();
}
```
```
Error:(449, 44) error: AutoValue property bar is not primitive, Parcelable, or Serializable.
```

### PR DESCRIPTION
**Pull request by rharter**

### CODE REVIEW

File: src/main/java/com/ryanharter/auto/value/parcel/AutoValueParcelExtension.java [hunk 1]
```diff
@@ -83,11 +86,24 @@ String getParcelableCode(Context context, String className, String classToExtend
 
   private void validateProperties(ProcessingEnvironment env,
                                   Map<String, ExecutableElement> properties) {
+    Types typeUtils = env.getTypeUtils();
+    Elements elementUtils = env.getElementUtils();
+    TypeMirror collection = typeUtils.getDeclaredType(
+        elementUtils.getTypeElement(Collection.class.getName()),
```
Comment (mattprecious) [inline src/main/java/com/ryanharter/auto/value/parcel/AutoValueParcelExtension.java]: I think you should specifically check for `List` instead of `Collection`. `Parcel` special cases `List` by using the `writeList()` method. Collections on the other hand are only parcelable if their type parameter is serializable.

Check out the implementation of `Parcel#writeValue()`. It has a lot of special cases.

Comment (JakeWharton) [inline src/main/java/com/ryanharter/auto/value/parcel/AutoValueParcelExtension.java]: Shouldn't this be more narrow at just `List`? The `Parcel` methods require a list so a `Set` or just `Collection` wouldn't be acceptable. Granted, most implementations of these types are likely to be `Serializable` themselves, but I don't think we can rely on that.

**Comment by JakeWharton** [comment]
This LGTM, but there's still valid Parcel types which probably get detected as invalid. For example, `SparseBooleanArray`, `SparseArray`, `PersistableBundle`, `Size`, `SizeF`...

**Comment by rharter** [comment]
I'm going to merge this and open an issue to cover everything else.

**Comment by JakeWharton** [comment]
:+1: This was our only blocker anyway.
